### ISSUE TITLE
iTunespass

### ISSUE THREAD

**Issue by Kamo477** [ioan-ghisoi-cko/integration-tutorial#1]

**Comment by Kamo477** [comment]
Can you pls help me?

**Comment by ioan-ghisoi-cko** [comment]
There is no info on this issue. Can you give me some details?

**Comment by Kamo477** [comment]
- Yes how can i use my iTunes Pass for pay

**Comment by Kamo477** [comment]
Apple Id That i can use for pay?

**Comment by ioan-ghisoi-cko** [comment]
You need to have an apple developer account, and follow the steps here -> https://www.checkout.com/docs/payments/payment-methods/wallets/apple-pay/set-up-apple-pay

**Comment by Kamo477** [comment]
Access Unavailable

This resource is only for developers enrolled in a developer program or members of an organization’s team in a developer program.

**Comment by Kamo477** [comment]
Thx so much its ok i will Never understand that i,m from another Generation
